# Generated by Django 5.1.5 on 2025-02-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paypal_sale_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
